function generate_figures(figures_to_generate)

% list here the figures to generate (specifying the function file names)
if nargin < 1
    figures_to_generate = { ...
      'ILSVRC2012_1000_VAL_mean_recall', ...
      'ILSVRC2012_1000_VAL_mean_precision', ...
      'PASCAL2007_TRAINVAL_mean_recall', ...
      'PASCAL2007_TRAINVAL_mean_precision', ...
      'PASCAL2007_TEST_mean_recall', ...
      'PASCAL2007_TEST_mean_precision', ...
      'ILSVRC2012_200rnd_VAL_mean_recall', ...
      'ILSVRC2012_200rnd_VAL_mean_precision', ...
      'ILSVRC2012_200rnd_v_1000_VAL_mean_recall', ...
      'ILSVRC2012_200rnd_v_1000_VAL_mean_precision', ...
      'ILSVRC2012_200rnd_TRAIN_mean_recall', ...
      'ILSVRC2012_200rnd_TRAIN_mean_precision', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_GT_OBFSgt', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_GT_SS', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_diff_GT_OBFSgt', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_diff_OBFSgt_BING',...
      'ILSVRC2012_200rnd_VAL_detection_AP_diff_OBFSgt_SS', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_best_worst_categories', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_best_worst_categories_top_1', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_best_worst_cat_with_STL_test',...
      'ILSVRC2012_200rnd_VAL_detection_AP_GT_OBFSgt_top_1', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_OBFSgt_BING_top_1', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_OBFSgt_BING_top_3', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_OBFSgt_FULLIMAGE_top_1', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_OBFSgt_SS_top_1', ...
      'ILSVRC2012_200rnd_VAL_detection_AP_diff_OBFSgt_testing_SS',...
      };
end

path_scripts = './utils_generate_figures_paper';
close all
addpath([path_scripts '/export_fig']);
addpath(path_scripts);

for i=1:numel(figures_to_generate)
  generate_figure(figures_to_generate{i});
end

end


function generate_figure(name)
fname = ['./figures/' name];
fprintf('*** Generating figure %s and saving it to %s\n', name, fname);
eval(name);
% save EPS
eval(['print2eps ' fname '.eps'])
% save FIG
%saveas(gcf, [fname '.fig']);
close(gcf);
end


