function generate_figures()

% list here the figures to generate (specifying the function file names)
figures_to_generate = { ...
  'ILSVRC2012_1000_VAL_mean_recall', ...
  'ILSVRC2012_1000_VAL_mean_precision', ...
  'PASCAL2007_TRAINVAL_mean_recall', ...
  'PASCAL2007_TRAINVAL_mean_precision', ...
  'PASCAL2007_TEST_mean_recall', ...
  'PASCAL2007_TEST_mean_precision', ...
  'ILSVRC2012_200rnd_VAL_mean_recall', ...
  'ILSVRC2012_200rnd_VAL_mean_precision', ...
  'ILSVRC2012_200rnd_TRAIN_mean_recall', ...
  'ILSVRC2012_200rnd_TRAIN_mean_precision', ...
  };


close all
addpath([pwd '/export_fig']);

for i=1:numel(figures_to_generate)
  generate_figure(figures_to_generate{i});
end

end

function generate_figure(name)
fname = ['./figures/' name];
eval(name);
eval(['print2eps ' fname '.eps'])
saveas(gcf, [fname '.fig']);
close(gcf);
end


